/**
 * Complete Event Type Mappings for Aritech ATS Alarm Panel
 * Extracted from decompiled Android app sources
 * 357 event types total
 */

// Event type enum with descriptions
export const EVENT_TYPES = {
    0: { code: 'ev_NULL', name: 'NULL', category: 'Ignored' },
    1: { code: 'ev_AN', name: 'Detector dirty restore', category: 'Restore' },
    2: { code: 'ev_ARZN', name: 'AC restore (Technical Zone)', category: 'Restore' },
    3: { code: 'ev_ARDGP', name: 'AC Restore', category: 'Restore' },
    4: { code: 'ev_AS', name: 'Detector dirty', category: 'Trouble' },
    5: { code: 'ev_ATZN', name: 'AC trouble (Technical Zone)', category: 'Trouble' },
    6: { code: 'ev_ATDGP', name: 'AC Fault', category: 'Trouble' },
    7: { code: 'ev_BA', name: 'Alarm', category: 'Alarm' },
    8: { code: 'ev_BB', name: 'Alarm inhibit', category: 'Info' },
    9: { code: 'ev_BCUSER', name: 'Cancel by user', category: 'Access' },
    10: { code: 'ev_BCKEY', name: 'Cancel by key', category: 'Access' },
    11: { code: 'ev_BCPC', name: 'Cancel by PC', category: 'Access' },
    12: { code: 'ev_BJ', name: 'Detector supervision restore', category: 'Restore' },
    13: { code: 'ev_BR', name: 'Burglar restore', category: 'Restore' },
    14: { code: 'ev_BT', name: 'Input in mask/trouble when disarmed', category: 'Trouble' },
    15: { code: 'ev_BU', name: 'Alarm uninhibit', category: 'Info' },
    16: { code: 'ev_BV', name: 'Alarm confirm', category: 'Alarm' },
    17: { code: 'ev_BW', name: 'Restore confirmed alarm', category: 'Restore' },
    18: { code: 'ev_BZ', name: 'Detector supervision', category: 'Trouble' },
    19: { code: 'ev_CFUSER', name: 'Forced set by user', category: 'Set_Partset' },
    20: { code: 'ev_CFKEY', name: 'Forced set by key', category: 'Set_Partset' },
    21: { code: 'ev_CFPC', name: 'Forced set by PC', category: 'Set_Partset' },
    22: { code: 'ev_CGUSER', name: 'Part set by user', category: 'Set_Partset' },
    23: { code: 'ev_CGKEY', name: 'Part set by key', category: 'Set_Partset' },
    24: { code: 'ev_CGPC', name: 'Part set by PC', category: 'Set_Partset' },
    25: { code: 'ev_CLUSER', name: 'Set by user', category: 'Set_Partset' },
    26: { code: 'ev_CLKEY', name: 'Set by key', category: 'Set_Partset' },
    27: { code: 'ev_CLPC', name: 'Set by PC', category: 'Set_Partset' },
    28: { code: 'ev_EEUSER', name: 'Exit fault by user', category: 'Alarm' },
    29: { code: 'ev_EESYST', name: 'Exit fault by system', category: 'Info' },
    30: { code: 'ev_ERDGP', name: 'Expander trouble restore', category: 'Info' },
    31: { code: 'ev_ERDGPC', name: 'Expander communication restore', category: 'Restore' },
    32: { code: 'ev_ERDGPF', name: 'Expander fuse restore', category: 'Restore' },
    33: { code: 'ev_ERRAS', name: 'Keypad trouble restore', category: 'Restore' },
    34: { code: 'ev_ERRASC', name: 'Keypad communication restore', category: 'Restore' },
    35: { code: 'ev_ETDGP', name: 'Expander trouble', category: 'Trouble' },
    36: { code: 'ev_ETDGPC', name: 'Expander communication fail', category: 'Info' },
    37: { code: 'ev_ETDGPF', name: 'Expander fuse fault', category: 'Trouble' },
    38: { code: 'ev_ETRAS', name: 'Keypad trouble', category: 'Trouble' },
    39: { code: 'ev_ETRASC', name: 'Keypad communication fail', category: 'Info' },
    40: { code: 'ev_FA', name: 'Fire', category: 'Alarm' },
    41: { code: 'ev_FB', name: 'Fire inhibit', category: 'Info' },
    42: { code: 'ev_FJ', name: 'Fire trouble restore', category: 'Restore' },
    43: { code: 'ev_FR', name: 'Fire restore', category: 'Restore' },
    44: { code: 'ev_FT', name: 'Fire trouble', category: 'Trouble' },
    45: { code: 'ev_FU', name: 'Fire uninhibit', category: 'Info' },
    46: { code: 'ev_FW', name: 'Fire supervision long', category: 'Trouble' },
    47: { code: 'ev_HA', name: 'Duress', category: 'Alarm' },
    48: { code: 'ev_HR', name: 'Duress restore', category: 'Restore' },
    49: { code: 'ev_JP', name: 'Service in', category: 'Info' },
    50: { code: 'ev_JR', name: 'Service out', category: 'Info' },
    51: { code: 'ev_JT', name: 'Time changed', category: 'Info' },
    52: { code: 'ev_LB', name: 'Local programming start', category: 'Info' },
    53: { code: 'ev_LS', name: 'Local programming stop', category: 'Info' },
    54: { code: 'ev_LR', name: 'Line restore', category: 'Restore' },
    55: { code: 'ev_LT', name: 'Line fault', category: 'Trouble' },
    56: { code: 'ev_MA', name: 'Medical alarm', category: 'Alarm' },
    57: { code: 'ev_MB', name: 'Medical bypass', category: 'Info' },
    58: { code: 'ev_MJ', name: 'Medical supervision restore', category: 'Restore' },
    59: { code: 'ev_MR', name: 'Medical restore', category: 'Restore' },
    60: { code: 'ev_MU', name: 'Medical unbypass', category: 'Info' },
    61: { code: 'ev_MS', name: 'Medical supervision long', category: 'Trouble' },
    62: { code: 'ev_OPUSER', name: 'Unset by user', category: 'Unset' },
    63: { code: 'ev_OPKEY', name: 'Unset by key', category: 'Unset' },
    64: { code: 'ev_OPPC', name: 'Unset by PC', category: 'Unset' },
    65: { code: 'ev_ORUSER', name: 'Unset from alarm by user', category: 'Unset' },
    66: { code: 'ev_ORKEY', name: 'Unset from alarm by key', category: 'Unset' },
    67: { code: 'ev_ORPC', name: 'Unset from alarm by PC', category: 'Unset' },
    68: { code: 'ev_PA', name: 'Panic', category: 'Alarm' },
    69: { code: 'ev_PB', name: 'Panic bypass', category: 'Info' },
    70: { code: 'ev_PJ', name: 'Panic trouble restore', category: 'Restore' },
    71: { code: 'ev_PR', name: 'Panic restore', category: 'Restore' },
    72: { code: 'ev_PT', name: 'Panic trouble', category: 'Trouble' },
    73: { code: 'ev_PU', name: 'Panic unbypass', category: 'Info' },
    74: { code: 'ev_RB', name: 'Remote programming start', category: 'Info' },
    75: { code: 'ev_RR', name: 'Power up system', category: 'Info' },
    76: { code: 'ev_RRDGP', name: 'Power up Expander', category: 'Info' },
    77: { code: 'ev_RRRAS', name: 'Power up Keypad', category: 'Info' },
    78: { code: 'ev_RS', name: 'Remote programming success', category: 'Info' },
    79: { code: 'ev_RU', name: 'Remote programming fail', category: 'Info' },
    80: { code: 'ev_RX', name: 'Manual CS test', category: 'Info' },
    81: { code: 'ev_TA', name: 'Tamper zone', category: 'Alarm' },
    82: { code: 'ev_TADGP', name: 'Tamper Expander', category: 'Alarm' },
    83: { code: 'ev_TADGPS', name: 'Tamper Expander siren', category: 'Trouble' },
    84: { code: 'ev_TARAS', name: 'Tamper Keypad', category: 'Alarm' },
    85: { code: 'ev_TB', name: 'Tamper bypass', category: 'Info' },
    86: { code: 'ev_TR', name: 'Tamper zone restore', category: 'Restore' },
    87: { code: 'ev_TRDGP', name: 'Tamper Expander restore', category: 'Restore' },
    88: { code: 'ev_TRDGPS', name: 'Tamper Expander siren restore', category: 'Restore' },
    89: { code: 'ev_TRRAS', name: 'Tamper Keypad restore', category: 'Restore' },
    90: { code: 'ev_TU', name: 'Tamper unbypass', category: 'Info' },
    91: { code: 'ev_UBDGP', name: 'Expander bypass', category: 'Info' },
    92: { code: 'ev_UBRAS', name: 'Keypad bypass', category: 'Info' },
    93: { code: 'ev_UBZN', name: 'Zone bypass', category: 'Info' },
    94: { code: 'ev_UUDGP', name: 'Expander unbypass', category: 'Info' },
    95: { code: 'ev_UURAS', name: 'Keypad unbypass', category: 'Info' },
    96: { code: 'ev_UUZN', name: 'Zone unbypass', category: 'Info' },
    97: { code: 'ev_WP', name: 'Walk test passed', category: 'Info' },
    98: { code: 'ev_WF', name: 'Walk test fault', category: 'Info' },
    99: { code: 'ev_XH', name: 'RF jamming restore', category: 'Restore' },
    100: { code: 'ev_XQ', name: 'RF jamming', category: 'Trouble' },
    101: { code: 'ev_XR', name: 'Detector low battery restore', category: 'Restore' },
    102: { code: 'ev_XT', name: 'Detector low battery', category: 'Trouble' },
    103: { code: 'ev_YC', name: 'Communications device fault', category: 'Trouble' },
    104: { code: 'ev_YK', name: 'FTC restore', category: 'Restore' },
    105: { code: 'ev_YR', name: 'Battery restore', category: 'Restore' },
    106: { code: 'ev_YS', name: 'FTC', category: 'Trouble' },
    107: { code: 'ev_YT', name: 'Battery fault', category: 'Trouble' },
    108: { code: 'ev_ZA', name: 'Technical', category: 'Alarm' },
    109: { code: 'ev_ZB', name: 'Technical bypass', category: 'Info' },
    110: { code: 'ev_ZJ', name: 'Technical supervision restore', category: 'Restore' },
    111: { code: 'ev_ZR', name: 'Technical restore', category: 'Restore' },
    112: { code: 'ev_ZS', name: 'Technical supervision long', category: 'Trouble' },
    113: { code: 'ev_ZU', name: 'Technical unbypass', category: 'Info' },
    114: { code: 'ev_OUTA', name: 'Output activated', category: 'Info' },
    115: { code: 'ev_OUTR', name: 'Output restored', category: 'Restore' },
    116: { code: 'ev_USRG', name: 'User access granted', category: 'Access' },
    117: { code: 'ev_USRD', name: 'User access denied', category: 'Access' },
    118: { code: 'ev_EROK', name: 'Engineer reset', category: 'Restore' },
    119: { code: 'ev_INTEG', name: 'Stack integrity error', category: 'Trouble' },
    120: { code: 'ev_WDG', name: 'Watchdog error', category: 'Trouble' },
    121: { code: 'ev_CHKSUM', name: 'Flash memory checksum error', category: 'Trouble' },
    122: { code: 'ev_USRADD', name: 'User added', category: 'Info' },
    123: { code: 'ev_USRDEL', name: 'User deleted', category: 'Info' },
    124: { code: 'ev_USRPIN', name: 'PIN changed', category: 'Info' },
    125: { code: 'ev_USRTAMP', name: 'PIN tamper', category: 'Alarm' },
    126: { code: 'ev_ZNNTST', name: 'Zone not tested', category: 'Info' },
    127: { code: 'ev_BJS', name: 'Detector supervision restore', category: 'Restore' },
    128: { code: 'ev_BZS', name: 'Detector supervision', category: 'Trouble' },
    129: { code: 'ev_INSTRST', name: 'Recovery proc', category: 'Info' },
    130: { code: 'ev_TT', name: 'Key box open', category: 'Alarm' },
    131: { code: 'ev_KBTR', name: 'Key box restore', category: 'Restore' },
    132: { code: 'ev_YTL', name: 'Battery low', category: 'Trouble' },
    133: { code: 'ev_OVRD', name: 'Fault/Alarm overrided', category: 'Info' },
    134: { code: 'ev_YA', name: 'Tamper Expander siren', category: 'Trouble' },
    135: { code: 'ev_YH', name: 'Tamper Expander siren restore', category: 'Restore' },
    136: { code: 'ev_NC', name: 'CS poll fault', category: 'Trouble' },
    137: { code: 'ev_NR', name: 'CS poll restored', category: 'Restore' },
    138: { code: 'ev_LTETH', name: 'ETH link fault', category: 'Trouble' },
    139: { code: 'ev_LTIP', name: 'IP config fault', category: 'Trouble' },
    140: { code: 'ev_LRIP', name: 'IP configured', category: 'Restore' },
    141: { code: 'ev_JTSYS', name: 'Time changed', category: 'Info' },
    142: { code: 'ev_YSSYS', name: 'Global FTC', category: 'Trouble' },
    143: { code: 'ev_YKSYS', name: 'Global FTC restore', category: 'Restore' },
    144: { code: 'ev_RP', name: 'Automatic CS test', category: 'Info' },
    145: { code: 'ev_SMSUN', name: 'Unknown SMS', category: 'Info' },
    146: { code: 'ev_SMSLIM', name: 'SMS sending limit reached', category: 'Trouble' },
    147: { code: 'ev_YKMI', name: 'Communications device restore', category: 'Restore' },
    148: { code: 'ev_LTGPRS', name: 'GPRS link fault', category: 'Trouble' },
    149: { code: 'ev_LTIPGPRS', name: 'GPRS IP config fault', category: 'Trouble' },
    150: { code: 'ev_LRIPGPRS', name: 'GPRS IP configured', category: 'Restore' },
    151: { code: 'ev_CFRAS', name: 'Quick set', category: 'Set_Partset' },
    152: { code: 'ev_CGRAS', name: 'Quick part set', category: 'Set_Partset' },
    153: { code: 'ev_CP', name: 'Auto set', category: 'Set_Partset' },
    154: { code: 'ev_OA', name: 'Auto unset', category: 'Unset' },
    155: { code: 'ev_OT', name: 'Late close', category: 'Alarm' },
    156: { code: 'ev_OK', name: 'Early open', category: 'Alarm' },
    157: { code: 'ev_AASTOPU', name: 'Autoset stopped by user', category: 'Unset' },
    158: { code: 'ev_AASTOPS', name: 'Autoset stopped by system', category: 'Unset' },
    159: { code: 'ev_PARAS', name: 'Panic', category: 'Alarm' },
    160: { code: 'ev_PAUSR', name: 'Panic', category: 'Alarm' },
    161: { code: 'ev_IA', name: 'Engineer reset required', category: 'Trouble' },
    162: { code: 'ev_CA', name: 'Card assigned', category: 'Info' },
    163: { code: 'ev_CR', name: 'Card removed', category: 'Info' },
    164: { code: 'ev_GA', name: 'Gas alarm', category: 'Alarm' },
    165: { code: 'ev_GR', name: 'Gas alarm restore', category: 'Restore' },
    166: { code: 'ev_GB', name: 'Gas alarm inhibit', category: 'Info' },
    167: { code: 'ev_GU', name: 'Gas alarm uninhibit', category: 'Info' },
    168: { code: 'ev_GS', name: 'Gas zone supervision', category: 'Alarm' },
    169: { code: 'ev_GJ', name: 'Gas supervision restore', category: 'Restore' },
    170: { code: 'ev_KA', name: 'Heat alarm', category: 'Alarm' },
    171: { code: 'ev_KR', name: 'Heat alarm restore', category: 'Restore' },
    172: { code: 'ev_KB', name: 'Heat alarm inhibit', category: 'Info' },
    173: { code: 'ev_KU', name: 'Heat alarm uninhibit', category: 'Info' },
    174: { code: 'ev_KS', name: 'Heat zone supervision', category: 'Alarm' },
    175: { code: 'ev_KJ', name: 'Heat supervision restore', category: 'Restore' },
    176: { code: 'ev_WA', name: 'Water alarm', category: 'Alarm' },
    177: { code: 'ev_WR', name: 'Water alarm restore', category: 'Restore' },
    178: { code: 'ev_WB', name: 'Water alarm inhibit', category: 'Info' },
    179: { code: 'ev_WU', name: 'Water alarm uninhibit', category: 'Info' },
    180: { code: 'ev_WS', name: 'Water zone supervision', category: 'Alarm' },
    181: { code: 'ev_WJ', name: 'Water supervision restore', category: 'Restore' },
    182: { code: 'ev_CLRAS', name: 'Set by user', category: 'Info' },
    183: { code: 'ev_HV', name: 'Confirmed panic alarm', category: 'Alarm' },
    184: { code: 'ev_HW', name: 'Restore confirmed panic alarm', category: 'Restore' },
    185: { code: 'ev_EEZONE', name: 'Exit fault by zone', category: 'Alarm' },
    186: { code: 'ev_UA', name: 'Generic technical alarm', category: 'Alarm' },
    187: { code: 'ev_UR', name: 'Generic technical alarm restore', category: 'Restore' },
    188: { code: 'ev_FARAS', name: 'Fire', category: 'Alarm' },
    189: { code: 'ev_MARAS', name: 'Medical alarm', category: 'Alarm' },
    190: { code: 'ev_FRRAS', name: 'Fire restore', category: 'Restore' },
    191: { code: 'ev_MRRAS', name: 'Medical restore', category: 'Restore' },
    192: { code: 'ev_PRRAS', name: 'Panic restore', category: 'Restore' },
    193: { code: 'ev_PRUSR', name: 'Panic restore', category: 'Restore' },
    194: { code: 'ev_PICRQ', name: 'Picture requested from expander', category: 'Info' },
    195: { code: 'ev_PICTKN', name: 'Picture taken and stored on expander', category: 'Picture' },
    196: { code: 'ev_PICSNT', name: 'Pic sent OH', category: 'Info' },
    197: { code: 'ev_OHKM', name: 'Encryption key mismatch between ATS Panel and OH receiver', category: 'Trouble' },
    198: { code: 'ev_PICGPRSLIM', name: 'Picture reports over GPRS limit reached', category: 'Picture' },
    199: { code: 'ev_PICETHLIM', name: 'Picture reports over ETH limit reached', category: 'Picture' },
    200: { code: 'ev_PICLIM', name: 'Picture limit exceeded', category: 'Picture' },
    201: { code: 'ev_PEBMEMFULL', name: 'ATS1238 picture memory is full', category: 'Picture' },
    202: { code: 'ev_PEBMEMWRC90P', name: 'ATS1238 flash memory reached 90% of write cycles', category: 'Trouble' },
    203: { code: 'ev_GETIMGFAIL', name: 'Failed to get picture from the ATS1238', category: 'Picture' },
    204: { code: 'ev_PICDEL', name: 'Pictures deleted from ATS1238 and cameras', category: 'Info' },
    205: { code: 'ev_CAMMODEFAIL', name: 'Setting of camera mode failed', category: 'Trouble' },
    206: { code: 'ev_TS', name: 'Test Start', category: 'Info' },
    207: { code: 'ev_TE', name: 'Test End', category: 'Info' },
    208: { code: 'ev_LU', name: 'Local programming fail', category: 'Trouble' },
    209: { code: 'ev_BRAM', name: 'Detector masked restore', category: 'Restore' },
    210: { code: 'ev_BTAM', name: 'Detector masked when disarmed', category: 'Trouble' },
    211: { code: 'ev_BRFT', name: 'Detector fault restore', category: 'Restore' },
    212: { code: 'ev_BTFT', name: 'Detector fault when disarmed', category: 'Trouble' },
    213: { code: 'ev_PICMMSLIM', name: 'MMS reports limit reached', category: 'Trouble' },
    214: { code: 'ev_TSDGP', name: 'Test Start', category: 'Info' },
    215: { code: 'ev_TEDGP', name: 'Test End', category: 'Info' },
    216: { code: 'ev_TSSYS', name: 'Test Start', category: 'Info' },
    217: { code: 'ev_TESYS', name: 'Test End', category: 'Info' },
    218: { code: 'ev_YPDGP', name: 'Power supply trouble', category: 'Trouble' },
    219: { code: 'ev_YQDGP', name: 'Power supply restored', category: 'Restore' },
    220: { code: 'ev_XHDL', name: 'RF jamming restore (dialler)', category: 'Restore' },
    221: { code: 'ev_XQDL', name: 'RF jamming (dialler)', category: 'Trouble' },
    222: { code: 'ev_XRFOB', name: 'Fob low battery restore', category: 'Restore' },
    223: { code: 'ev_XTFOB', name: 'Fob low battery', category: 'Trouble' },
    224: { code: 'ev_TAAM', name: 'Detector masked when unset', category: 'Alarm' },
    225: { code: 'ev_TRAM', name: 'Detector masked restore', category: 'Alarm' },
    226: { code: 'ev_TAFT', name: 'Detector fault when unset', category: 'Alarm' },
    227: { code: 'ev_TRFT', name: 'Detector fault restore', category: 'Alarm' },
    228: { code: 'ev_BVDGP', name: 'Alarm confirm (Exp)', category: 'Alarm' },
    229: { code: 'ev_BVDGPS', name: 'Alarm confirm (DGP siren)', category: 'Alarm' },
    230: { code: 'ev_BVRAS', name: 'Alarm confirm (Rkp)', category: 'Alarm' },
    231: { code: 'ev_BWDGP', name: 'Restore confirmed alarm (Exp)', category: 'Restore' },
    232: { code: 'ev_BWDGPS', name: 'Restore confirmed alarm (DGP siren)', category: 'Restore' },
    233: { code: 'ev_BWRAS', name: 'Restore confirmed alarm (Rkp)', category: 'Restore' },
    234: { code: 'ev_HAZN', name: 'Duress (Zone)', category: 'Alarm' },
    235: { code: 'ev_HRZN', name: 'Duress restore (Zone)', category: 'Restore' },
    236: { code: 'ev_BVRASC', name: 'Alarm Confirm from Keypad Communication Fail', category: 'Alarm' },
    237: { code: 'ev_BVDGPC', name: 'Alarm Confirm from Expander Communication Fail', category: 'Alarm' },
    238: { code: 'ev_BWRASC', name: 'Restore Confirmed Alarm from Keypad Communication Fail', category: 'Alarm' },
    239: { code: 'ev_BWDGPC', name: 'Restore Confirmed Alarm from Expander Communication Fail', category: 'Alarm' },
    240: { code: 'ev_YTZN', name: 'Aux batt fault', category: 'Trouble' },
    241: { code: 'ev_YRZN', name: 'Aux batt rest.', category: 'Restore' },
    242: { code: 'ev_YPOVDGP', name: 'Power supply overvoltage trouble (Exp)', category: 'Trouble' },
    243: { code: 'ev_YTDGP', name: 'Battery test on DGP failed', category: 'Trouble' },
    244: { code: 'ev_YRDGP', name: 'Battery test on DGP passed', category: 'Info' },
    245: { code: 'ev_REP_SUCCESS', name: 'Report OK', category: 'Info' },
    246: { code: 'ev_REP_FAIL', name: 'Report Fail', category: 'Trouble' },
    247: { code: 'ev_REP_CONNFAIL', name: 'Connect Fail', category: 'Trouble' },
    248: { code: 'ev_YRDL', name: 'Dlr Batt.Rest', category: 'Restore' },
    249: { code: 'ev_YTDL', name: 'Dlr Batt.Fail', category: 'Trouble' },
    250: { code: 'ev_YCMIDL', name: 'Communications device fault', category: 'Trouble' },
    251: { code: 'ev_YKMIDL', name: 'Communications device restore', category: 'Restore' },
    252: { code: 'ev_YCMOD', name: 'Module reset', category: 'Info' },
    253: { code: 'ev_YKMOD', name: 'Module ready', category: 'Info' },
    254: { code: 'ev_ALTCBACKPC', name: 'Alternate PC connection established', category: 'Info' },
    255: { code: 'ev_INHLIM', name: 'Inhibit limit', category: 'Trouble' },
    256: { code: 'ev_ISOLLIM', name: 'Isolate limit', category: 'Trouble' },
    257: { code: 'ev_SHULIM', name: 'Shunt limit', category: 'Trouble' },
    258: { code: 'ev_INHLIMR', name: 'Inhibit limit restore', category: 'Restore' },
    259: { code: 'ev_ISOLLIMR', name: 'Isolate limit restore', category: 'Restore' },
    260: { code: 'ev_SHULIMR', name: 'Shunt limit restore', category: 'Restore' },
    261: { code: 'ev_ISOLLIMF', name: 'Isolate limit fault', category: 'Restore' },
    262: { code: 'ev_ISOLLIMFR', name: 'Isolate limit fault restore', category: 'Restore' },
    263: { code: 'ev_ATMEXTTIME', name: 'Extended Unset time', category: 'Info' },
    264: { code: 'ev_ATMFAILCLOSE', name: 'Failed Auto Set (ATM)', category: 'Trouble' },
    265: { code: 'ev_DETTESTOK', name: 'Det. Test OK', category: 'Info' },
    266: { code: 'ev_DETTESTFAIL', name: 'Det.Test Fail', category: 'Info' },
    267: { code: 'ev_DETTSTZNOK', name: 'Det. Tested', category: 'Info' },
    268: { code: 'ev_DETTSTZNFAIL', name: 'Det.Test Fail', category: 'Info' },
    269: { code: 'ev_AEXITSTOP', name: 'Area Exit Time Stoppped', category: 'Info' },
    270: { code: 'ev_BATTREP', name: 'Battery replacement', category: 'Info' },
    271: { code: 'ev_BATTRES', name: 'Battery resistance', category: 'Info' },
    272: { code: 'ev_SHUNTMSTRON', name: 'Shunt Master ON', category: 'Info' },
    273: { code: 'ev_SHUNTMSTROFF', name: 'Shunt Master OFF', category: 'Info' },
    274: { code: 'ev_ZNSHUNTON', name: 'Shunt ON', category: 'Info' },
    275: { code: 'ev_ZNSHUNTOFF', name: 'Shunt Off', category: 'Info' },
    276: { code: 'ev_ZNSHUNTFLT', name: 'Shunt Fault', category: 'Trouble' },
    277: { code: 'ev_DUR', name: 'Dual Unset request', category: 'Unset' },
    278: { code: 'ev_RRREPFAIL', name: 'Power up reporting fail', category: 'Trouble' },
    279: { code: 'ev_RRREPFAILR', name: 'Power up reporting restore', category: 'Restore' },
    280: { code: 'ev_DD', name: 'Access denied, unknown code', category: 'Access' },
    281: { code: 'ev_IUM_NCARD', name: 'Access denied - IUM card not found', category: 'Ignored' },
    282: { code: 'ev_CODE_ENTER', name: 'PIN entered by user', category: 'Ignored' },
    283: { code: 'ev_USRG_FLOOR', name: 'Access granted: Floor', category: 'Ignored' },
    284: { code: 'ev_DOOR_AUNLOCK', name: 'Door unlocked - auto unlock', category: 'Ignored' },
    285: { code: 'ev_DOOR_ALOCK', name: 'Door locked - auto lock', category: 'Ignored' },
    286: { code: 'ev_DOOR_EGRESS', name: 'Request to exit granted at door', category: 'Ignored' },
    287: { code: 'ev_DOOR_DISABLE', name: 'Door disabled', category: 'Ignored' },
    288: { code: 'ev_DOOR_ENABLE', name: 'Door enabled', category: 'Ignored' },
    289: { code: 'ev_DOOR_UNSECURE', name: 'Door unlocked', category: 'Ignored' },
    290: { code: 'ev_DOOR_SECURE', name: 'Door closed and locked', category: 'Ignored' },
    291: { code: 'ev_DOOR_FORCED', name: 'Door forced', category: 'Ignored' },
    292: { code: 'ev_DOOR_FORCED_R', name: 'Door forced restored', category: 'Ignored' },
    293: { code: 'ev_DOOR_OPEN_TOL', name: 'Door open too long', category: 'Ignored' },
    294: { code: 'ev_DOOR_OPEN_TOL_R', name: 'Door open too long restored', category: 'Ignored' },
    295: { code: 'ev_DOOR_OPEN', name: 'Door open', category: 'Ignored' },
    296: { code: 'ev_DOOR_OPEN_R', name: 'Door open restored', category: 'Ignored' },
    297: { code: 'ev_HSU_TO_LESS', name: 'Too less HSU behind door.', category: 'Ignored' },
    298: { code: 'ev_HSU_TOO_LESS_R', name: 'Too few HSU behind door restored', category: 'Ignored' },
    299: { code: 'ev_HSU_ALARM', name: 'Too few HSU behind door - warning activated', category: 'Ignored' },
    300: { code: 'ev_HSU_ALARM_R', name: 'Too few HSU behind door - warning stopped', category: 'Ignored' },
    301: { code: 'ev_USR_ULOCK_DOOR', name: 'Door unlocked by user', category: 'Ignored' },
    302: { code: 'ev_USR_LOCK_DOOR', name: 'Door locked by user', category: 'Ignored' },
    303: { code: 'ev_USRG_SPASS', name: 'Access granted: soft passback', category: 'Ignored' },
    304: { code: 'ev_USRG_REGION', name: 'Access granted: region', category: 'Ignored' },
    305: { code: 'ev_USRG_TIM_IN', name: 'Access granted: time in', category: 'Ignored' },
    306: { code: 'ev_USRG_TIM_OUT', name: 'Access granted: time out', category: 'Ignored' },
    307: { code: 'ev_USRD_SYSCODE', name: 'Access denied: invalid site code', category: 'Ignored' },
    308: { code: 'ev_USRD_CODE', name: 'Access denied: invalid code', category: 'Ignored' },
    309: { code: 'ev_USRD_DOOR', name: 'Access denied: invalid door', category: 'Ignored' },
    310: { code: 'ev_USRD_TIMZN', name: 'Access denied: invalid timezone', category: 'Ignored' },
    311: { code: 'ev_USRD_AARM', name: 'Access denied: area not disarmed', category: 'Ignored' },
    312: { code: 'ev_USRD_HPASS', name: 'Access denied: hard passback', category: 'Ignored' },
    313: { code: 'ev_USRD_PIN', name: 'Access denied: invalid PIN', category: 'Ignored' },
    314: { code: 'ev_USRD_TWOCARDS', name: 'Access denied: two card violation', category: 'Ignored' },
    315: { code: 'ev_USRD_TIM_IN', name: 'Access denied: time in', category: 'Ignored' },
    316: { code: 'ev_USRD_TIM_OUT', name: 'Access denied: time out', category: 'Ignored' },
    317: { code: 'ev_USRD_HSR', name: 'Access denied: to few HSU users', category: 'Ignored' },
    318: { code: 'ev_TRACE_USR', name: 'User trace', category: 'Ignored' },
    319: { code: 'ev_TRACE_DOOR', name: 'Door trace', category: 'Ignored' },
    320: { code: 'ev_USRD_DCTRL', name: 'User access denied', category: 'Ignored' },
    321: { code: 'ev_USRG_DCTRL', name: 'User access granted', category: 'Ignored' },
    322: { code: 'ev_HA_DCTRL', name: 'Duress', category: 'Alarm' },
    323: { code: 'ev_HR_DCTRL', name: 'Duress restore', category: 'Restore' },
    324: { code: 'ev_RFUSTART', name: 'Remote firmware upgrade started', category: 'Info' },
    325: { code: 'ev_RFUFAIL', name: 'Remote firmware upgrade failed', category: 'Info' },
    326: { code: 'ev_RFUCANCEL', name: 'Remote firmware upgrade canceled', category: 'Info' },
    327: { code: 'ev_RFUOK', name: 'Remote firmware upgrade finished', category: 'Info' },
    328: { code: 'ev_TARDR', name: 'Reader tamper', category: 'Alarm' },
    329: { code: 'ev_TRRDR', name: 'Reader tamper restore', category: 'Restore' },
    330: { code: 'ev_ETRDRC', name: 'Reader communication fail', category: 'Trouble' },
    331: { code: 'ev_ERRDRC', name: 'Reader communication fail restore', category: 'Restore' },
    332: { code: 'ev_ERVOC', name: 'Audio device trouble restore', category: 'Restore' },
    333: { code: 'ev_ERVOCC', name: 'Audio device communication restore', category: 'Restore' },
    334: { code: 'ev_ETVOC', name: 'Audio trouble', category: 'Trouble' },
    335: { code: 'ev_ETVOCC', name: 'Audio device communication fail', category: 'Trouble' },
    336: { code: 'ev_RRVOC', name: 'Power up Audio device', category: 'Info' },
    337: { code: 'ev_TAVOC', name: 'Tamper Audio device', category: 'Alarm' },
    338: { code: 'ev_TRVOC', name: 'Tamper Audio device restore', category: 'Restore' },
    339: { code: 'ev_UBVOC', name: 'Audio device bypass', category: 'Info' },
    340: { code: 'ev_UUVOC', name: 'Audio device unbypass', category: 'Info' },
    341: { code: 'ev_BVVOC', name: 'Alarm confirm', category: 'Alarm' },
    342: { code: 'ev_BWVOC', name: 'Restore confirmed alarm', category: 'Restore' },
    343: { code: 'ev_BVVOCC', name: 'Alarm confirm', category: 'Alarm' },
    344: { code: 'ev_BWVOCC', name: 'Restore confirmed alarm', category: 'Restore' },
    345: { code: 'ev_HVRDR', name: 'Confirmed panic alarm', category: 'Alarm' },
    346: { code: 'ev_HWRDR', name: 'Restore confirmed panic alarm', category: 'Restore' },
    347: { code: 'ev_HVRAS', name: 'Confirmed panic alarm', category: 'Alarm' },
    348: { code: 'ev_HWRAS', name: 'Restore confirmed panic alarm', category: 'Restore' },
    349: { code: 'ev_HVDGP', name: 'Confirmed panic alarm', category: 'Alarm' },
    350: { code: 'ev_HWDGP', name: 'Restore confirmed panic alarm', category: 'Restore' },
    351: { code: 'ev_HVDGPS', name: 'Confirmed panic alarm', category: 'Alarm' },
    352: { code: 'ev_HWDGPS', name: 'Restore confirmed panic alarm', category: 'Restore' },
    353: { code: 'ev_BVDL', name: 'Alarm confirm', category: 'Alarm' },
    354: { code: 'ev_BWDL', name: 'Restore confirmed alarm', category: 'Restore' },
    355: { code: 'ev_HVDL', name: 'Confirmed panic alarm', category: 'Alarm' },
    356: { code: 'ev_HWDL', name: 'Restore confirmed panic alarm', category: 'Restore' }
};

// Class ID to readable string mapping (from CLASSID-MAPPING.md)
export const CLASS_ID_STRINGS = {
    0: 'Zone',
    1: 'Area',
    2: 'User Group',
    3: 'DGP',
    5: 'DGP0',
    6: 'User',
    7: 'Output',
    8: 'Panel',
    9: 'RAS',
    10: 'Central Station',
    11: 'PC Connection',
    14: 'Output',
    15: 'CEV Filter',
    16: 'User',
    17: 'System',
    19: 'Trigger',
    20: 'Calendar',
    25: 'FOB',
    26: 'Camera',
    32: 'Area Group',
    35: 'Region',
    36: 'Door',
    37: 'Door Group',
    39: 'Special Day',
    41: 'Reader',
    42: 'Audio Device',
    43: 'Notification'
};
